### ISSUE TITLE
Intersting project

### ISSUE THREAD

**Issue by LeiWang1999** [Pzzzzz5142/NLP-Inference-MM#5]
Seems like you wanna to do an implementation of int8 gemm to do NLP inference? I wonder why you choose to hands on wmma api to do int8 gemm instead of opensource library like cutlass or vendor library like cublas? I implemented some conflict-free int8 gemm kernels, maybe I can help you to implement it.

**Comment by Pzzzzz5142** [comment]
Thanks for your attention.

Sorry for the delay for I was writing a blog about how to implement sgemm and away from github for some days. The blog will be released next Monday. Once it's released, I will put the link in the readme. Check it out if you are interested.

This is just a demo project of how to implement a high performance gemm **Now**. I've tried to use it in NLP for I find that the performance of the cublas is quite slow. However, I find out that it's just because cublas/cutlass only support int8 tensor core with row/col major data layout. So I decided to rename the whole repository to Hands-on-GEMM making it becomes a GEMM tutorial project.

As for performance, I've moved to mma ptx in `PzzzzzDev` branch, and have achieved about 80%/110% performance compared to cublass/cutlass on large/small shape. So as you can see, there are still some mysterious problem pulling down the performance that I can't locate. I'd be appreciated if you can help.

**Comment by LeiWang1999** [comment]
yeah cutlass/cublas do not support i8 tensorcore instead of nt layouts because they can not be conflict free, ldmatrix can only transpose b16 data so they do not implement it. I'm currently focus on tensorize now, maybe we can have some deeper discussion.

**Comment by Pzzzzz5142** [comment]
Of course we can have a deeper discussion, you can add my QQ from my github profile just in case you need it.

**Comment by LeiWang1999** [comment]
@Pzzzzz5142 , I'm sorry because I seldom use qq now : (  I send my wechat id into your qqmail
